/**
 * hanoi.ts — side-elevation Tower of Hanoi (4 disks) solved correctly.
 *
 * The move list is generated by the real recursive algorithm; peg state is held
 * as stacks and every move is validated (only the top disk moves, never onto a
 * smaller one; must finish on the destination pole). The manipulator is a carriage
 * on a ceiling rail (prismatic) + a 2-link IK arm hanging below: it positions over
 * a pole, reaches down to the top ring, lifts it clear above the pole, traverses,
 * and lowers it onto the target pole. Spring-eased effector motion. Loops; reduced
 * motion shows the solved tower at rest.
 */

const REDUCED = "(prefers-reduced-motion: reduce)";
const REST_CX = 300;
const PIV = { x: 300, y: 52 };       // arm pivot, in carriage-local coords
const L1 = 175, L2 = 170;
const RAIL_MIN = 150, RAIL_MAX = 450;
const POLEX = [150, 300, 450];
const BASE_Y = 400, RH = 28;
const CARRY_Y = 138;                  // ring centre when lifted clear of the poles
const cy = (level: number) => BASE_Y - level * RH - 14;
const N = 4;

function solve(n: number, from: number, to: number, via: number, out: { disk: number; from: number; to: number }[] = []) {
  if (n === 0) return out;
  solve(n - 1, from, via, to, out);
  out.push({ disk: n, from, to });
  solve(n - 1, via, to, from, out);
  return out;
}

export function initHanoi(): void {
  if (typeof window === "undefined") return;
  const root = document.querySelector<HTMLElement>("#hanoi");
  if (!root) return;
  const carriage = root.querySelector<SVGGElement>("[data-carriage]");
  const upper = root.querySelector<SVGLineElement>("[data-upper]");
  const fore = root.querySelector<SVGLineElement>("[data-fore]");
  const elbowC = root.querySelector<SVGCircleElement>("[data-elbow]");
  const grip = root.querySelector<SVGGElement>("[data-grip]");
  const diskEls = new Map<number, SVGRectElement>();
  root.querySelectorAll<SVGRectElement>("[data-disk]").forEach((el) => diskEls.set(Number(el.dataset.size), el));
  if (!carriage || !upper || !fore || !elbowC || !grip || diskEls.size < N) return;

  const cur = { x: REST_CX, y: 220 };
  let cartX = REST_CX;
  let carry: SVGRectElement | null = null;
  const arm = { a1: Math.PI / 2, a2: 0 }; // hanging straight down at rest

  const ik = (tx: number, ty: number) => {
    let dx = tx - PIV.x, dy = ty - PIV.y;
    let D = Math.hypot(dx, dy);
    const maxR = L1 + L2 - 1, minR = Math.abs(L1 - L2) + 1;
    if (D > maxR) { dx *= maxR / D; dy *= maxR / D; D = maxR; }
    if (D < minR && D > 0) { dx *= minR / D; dy *= minR / D; D = minR; }
    const c2 = Math.max(-1, Math.min(1, (D * D - L1 * L1 - L2 * L2) / (2 * L1 * L2)));
    const m = Math.acos(c2);
    const opts = [m, -m].map((a2) => {
      let a1 = Math.atan2(dy, dx) - Math.atan2(L2 * Math.sin(a2), L1 + L2 * Math.cos(a2));
      while (a1 - arm.a1 > Math.PI) a1 -= 2 * Math.PI;
      while (a1 - arm.a1 < -Math.PI) a1 += 2 * Math.PI;
      return { a1, a2 };
    });
    const cost = (o: { a1: number; a2: number }) => Math.abs(o.a1 - arm.a1) + Math.abs(o.a2 - arm.a2);
    return cost(opts[0]) <= cost(opts[1]) ? opts[0] : opts[1];
  };

  const renderAll = () => {
    cartX += (Math.max(RAIL_MIN, Math.min(RAIL_MAX, cur.x)) - cartX) * 0.18;
    const cdx = cartX - REST_CX;
    carriage.setAttribute("transform", `translate(${cdx.toFixed(1)} 0)`);
    const t = ik(cur.x - cdx, cur.y);
    arm.a1 = t.a1; arm.a2 = t.a2;
    const ex = PIV.x + L1 * Math.cos(arm.a1), ey = PIV.y + L1 * Math.sin(arm.a1);
    const tx = ex + L2 * Math.cos(arm.a1 + arm.a2), ty = ey + L2 * Math.sin(arm.a1 + arm.a2);
    upper.setAttribute("x2", ex.toFixed(1)); upper.setAttribute("y2", ey.toFixed(1));
    fore.setAttribute("x1", ex.toFixed(1)); fore.setAttribute("y1", ey.toFixed(1));
    fore.setAttribute("x2", tx.toFixed(1)); fore.setAttribute("y2", ty.toFixed(1));
    elbowC.setAttribute("cx", ex.toFixed(1)); elbowC.setAttribute("cy", ey.toFixed(1));
    grip.setAttribute("transform", `translate(${tx.toFixed(1)} ${ty.toFixed(1)})`);
    if (carry) carry.setAttribute("transform", `translate(${cur.x.toFixed(1)} ${cur.y.toFixed(1)})`);
  };

  const springTo = (gx: number, gy: number, k = 0.24, damp = 0.52) =>
    new Promise<void>((res) => {
      let vx = 0, vy = 0, f = 0;
      const step = () => {
        vx = (vx + (gx - cur.x) * k) * damp;
        vy = (vy + (gy - cur.y) * k) * damp;
        cur.x += vx; cur.y += vy; renderAll(); f++;
        if ((Math.hypot(gx - cur.x, gy - cur.y) < 0.8 && Math.hypot(vx, vy) < 0.6) || f > 150) {
          cur.x = gx; cur.y = gy; renderAll(); res();
        } else requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    });

  const wait = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
  const wobble = (el: SVGRectElement, px: number, py: number) => {
    const t0 = performance.now(), D = 420;
    const step = (now: number) => {
      const kk = Math.min(1, (now - t0) / D);
      const s = 1 + 0.1 * Math.exp(-4 * kk) * Math.cos(kk * 13);
      el.setAttribute("transform", `translate(${px} ${py}) scale(${s.toFixed(3)})`);
      if (kk < 1) requestAnimationFrame(step); else el.setAttribute("transform", `translate(${px} ${py})`);
    };
    requestAnimationFrame(step);
  };

  const setDisk = (size: number, p: number, level: number) =>
    diskEls.get(size)!.setAttribute("transform", `translate(${POLEX[p]} ${cy(level)})`);
  const resetPegs = () => {
    const pegs: number[][] = [[4, 3, 2, 1], [], []];
    pegs.forEach((stack, p) => stack.forEach((size, level) => setDisk(size, p, level)));
    return pegs;
  };

  if (window.matchMedia(REDUCED).matches) {
    [4, 3, 2, 1].forEach((size, level) => setDisk(size, 2, level));
    renderAll();
    return;
  }

  async function solveOnce() {
    const pegs = resetPegs();
    const moves = solve(N, 0, 2, 1);
    console.log(`[Hanoi] ${moves.length} moves:`, moves.map((m) => `${m.disk}:${m.from}->${m.to}`).join(" "));
    for (const m of moves) {
      const from = pegs[m.from], to = pegs[m.to];
      if (from[from.length - 1] !== m.disk) console.error(`[Hanoi] ILLEGAL: top of peg ${m.from} is ${from[from.length - 1]}, not ${m.disk}`);
      if (to.length && to[to.length - 1] < m.disk) console.error(`[Hanoi] ILLEGAL: ${m.disk} onto smaller ${to[to.length - 1]}`);

      const el = diskEls.get(m.disk)!;
      const sx = POLEX[m.from], sy = cy(from.length - 1);
      const tx = POLEX[m.to], ty = cy(to.length);
      await springTo(sx, sy);                  // over the source pole, reach the top ring
      grip.classList.add("is-gripping"); el.classList.add("is-active");
      await wait(120);
      carry = el;
      await springTo(sx, CARRY_Y, 0.2, 0.56);  // lift clear of the pole
      await springTo(tx, CARRY_Y, 0.18, 0.6);  // traverse above the poles
      await springTo(tx, ty, 0.2, 0.56);       // lower onto the destination pole
      carry = null;
      el.setAttribute("transform", `translate(${tx} ${ty})`);
      grip.classList.remove("is-gripping");
      wobble(el, tx, ty);
      from.pop(); to.push(m.disk);
      await wait(90);
      el.classList.remove("is-active");
      await wait(200);
    }
    if (pegs[2].length === N && pegs[2].join() === "4,3,2,1") console.log("[Hanoi] solved: all disks on peg 2");
    else console.error("[Hanoi] did NOT finish correctly", JSON.stringify(pegs));
  }

  async function loop() {
    while (true) { await solveOnce(); await springTo(REST_CX, 220, 0.08, 0.72); await wait(2600); }
  }

  const io = new IntersectionObserver((entries) => {
    for (const e of entries) if (e.isIntersecting) { io.disconnect(); loop(); break; }
  }, { rootMargin: "0px 0px -15% 0px" });
  io.observe(root);
}
